version: '3.8'

services:
  eventmq:
    build: .
    volumes:
      - ./:/eventmq

  worker:
    image: eventmq_eventmq
    command: emq-jobmanager
    depends_on:
      - broker

  scheduler:
    image: eventmq_eventmq
    command: emq-scheduler
    depends_on:
      - broker

  broker:
    image: eventmq_eventmq
    command: emq-router
    ports:
      - "47290:47290"
      - "47291:47291"

